version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  descriptive_figures:
    run: r:latest analysis/report.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        figure: output/descriptive.png
  
  descriptive_tables:
    run: r:latest analysis/full_table_script.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table_one: output/Table1.html
        table_one_one: output/Table1-1.html
        table_one_two: output/Table1-2.html
        table_one_three: output/Table1-3.html
        table_one_four: output/Table1-4.html
        table_one_five: output/Table1-5.html
