version: '3.0'

expectations:
  population_size: 10000000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  cleaned_study_population:
    run: r:latest analysis/data_cleaning.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        csv: output/cleaned_df.RDS

  describe:
    run: r:latest analysis/report.R
    needs: [cleaned_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/descriptive.png

  descriptive_figures:
    run: r:latest analysis/ethnicity_fig.R
    needs: [cleaned_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/eth_descriptive.png